version: '3'

services:
  nodepp-example:
    build: .
    volumes:
      - .:/home/nodepp/nodepp
  # Scylla db
  scylladb:
    image: scylladb/scylla
    container_name: scylla-node
    ports:
      - "9042:9042"
