version: '3'

services:
  nodepp-example:
    build: .
    volumes:
      - .:/home/nodepp/nodepp
    command: bash -c "yarn run:native"

  # Scylla db
  scylladb:
    image: scylladb/scylla
    container_name: scylla-node
